Add option for annotation replies
julianhille/MuhammaraJS pull request #314
Opened 2023-07-13 06:01 UTC by joemoongit

Creating a draft pr for now. Still need to write test cases and may make modifications.

2023-07-13 06:03 UTC, julianhille commented
Are you fine when i run ci after v4 release?

2023-07-13 06:21 UTC, joemoongit commented
yes

2023-08-03 22:18 UTC, julianhille commented
damn also needs rebasing to be able to run in CI

2023-09-08 17:05 UTC, joemoongit commented
i’ve marked this pull request as ready. the annotation replies are working and they show up on pdfs. i've also updated how the annotations show up for the function text(). there are some more options we can add (i have commented them out for now) and optimizations we could make, but i will handle it in another pr, if that is okay with you. we could also add support for other types of annotations in later PRs.

2023-09-18 09:31 UTC, julianhille commented
will try this evening or tomorrow to get back to it, please remind me if i do not do this. sorry for the inconveniences

2023-09-20 05:32 UTC, joemoongit commented
do you have any suggestions? are you ok with the naming of some of the new variables such as 'replies' in AnnotOptions? also are you ok with me making some refactors/additions in later PRs?

2023-09-20 06:53 UTC, julianhille commented on lib/recipe/annotation.js
> +exports._annot = function _annot(subtype, args = {}, pageNumber, ref) {
has 4 function arguments but later you only call it with three, we should mark it opional. ahh ts is not supported. meh and its not public api

2023-09-20 06:53 UTC, julianhille commented on lib/recipe/annotation.js
> +    // wip
still wip?

2023-09-20 06:54 UTC, julianhille commented on tests/recipe/annotation-text.js
> +        title: "Guido van Rossum",
:>

2023-09-21 09:43 UTC, julianhille commented on lib/recipe/text.js
> + * @param {boolean} [options.open] - WIP
please update `WIP`

2023-09-21 09:45 UTC, julianhille requested changes
just a tiny bit to change overall good work thanks for the PR

2023-09-28 19:06 UTC, julianhille commented
Do you want me to wait requested changes?

2023-10-05 07:24 UTC, joemoongit commented
i will get back to you after this weekend. apologies for the delay

2023-10-12 21:32 UTC, joemoongit commented
i've made some updates to the options for annotation replies. it appears that the 'open' and 'icon' keys only pertain to text annotations of which are not replies. i've updated the documentation and test cases as well

2023-10-15 07:08 UTC, julianhille commented on lib/recipe/annotation.js
> +    // wip
Wip comment

2023-10-15 07:11 UTC, julianhille commented on lib/recipe/annotation.js
> + * @param {'Comment'|'Key'|'Note'|'Help'|'NewParagraph'|'Paragraph'|'Insert'} [options.icon] - The icon of annotation. Specific to text annotations. Default value: 'Note'
```suggestion
 * @param {'Comment'|'Key'|'Note'|'Help'|'NewParagraph'|'Paragraph'|'Insert'} [options.icon='Note'] - The icon of annotation. Specific to text annotations. Default value: 'Note'
```

2023-10-16 06:29 UTC, julianhille approved these changes

2023-10-16 16:59 UTC, joemoongit commented on lib/recipe/annotation.js
> +    // wip
no longer wip. annotation replies have the following properties: subtype, text, title, date, subject, richText, flag
latest commit does not have the comment

2023-10-16 21:07 UTC, merged