Was export PDFWStreamForBuffer missed in the definition?
julianhille/MuhammaraJS pull request #80
Opened 2021-04-25 03:04 UTC by jakefreeberg

I had to add this to my project to get hummus replaced with muhammara. I hope this helps your repo. Thank you for carrying the project forward.

2021-05-10 15:13 UTC, julianhille commented
Please add a changelog entry then we're good to go.

2021-05-10 15:30 UTC, julianhille requested changes

2021-05-10 15:30 UTC, julianhille commented on CHANGELOG.md
> +## [1.7.1] - 2021-05-10
Please remove this.
I'll add a date and version number as soon as I release

2021-05-10 15:30 UTC, julianhille commented on CHANGELOG.md
> +- More electron 11.x releases
Please revert this changes and below. 
if you'd like to lint this file open up a second pr and add a changelog entry.

Thank you for your time.

2021-05-11 15:17 UTC, jakefreeberg commented on CHANGELOG.md
> +- More electron 11.x releases
Sorry... my VSCode did more than I'd realized and still left a bit of format mess, but nothing seems to have visibly changed so hopefully we're good now.

2021-05-11 15:33 UTC, julianhille approved these changes
Please squash and then i merge. 

Thank you for your contribution

2021-05-12 21:48 UTC, merged

2021-05-13 01:47 UTC, jakefreeberg commented
Thank you for dealing with my mess here. I don't contribute to open source nearly as much as I should, but learned how to do a better job next time I do.